// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApHM3JpS3gnVj_FE7FjtPTkPnnAacLMPo',
    appId: '1:101051109032:web:91cd199faf2b873c30fc9d',
    messagingSenderId: '101051109032',
    projectId: 'cadastro-71443',
    authDomain: 'cadastro-71443.firebaseapp.com',
    storageBucket: 'cadastro-71443.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6WUJ4EjksnBuPoynLd48UpTWGXF0KFOQ',
    appId: '1:101051109032:android:19e7f587cacb1b8130fc9d',
    messagingSenderId: '101051109032',
    projectId: 'cadastro-71443',
    storageBucket: 'cadastro-71443.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKuki5G2qDaicnMrSBClathxp4MSec5BE',
    appId: '1:101051109032:ios:5ecae4033bcb245230fc9d',
    messagingSenderId: '101051109032',
    projectId: 'cadastro-71443',
    storageBucket: 'cadastro-71443.appspot.com',
    iosClientId: '101051109032-42dbikbnfi8mba3jd9rr28m2u99ln8o1.apps.googleusercontent.com',
    iosBundleId: 'com.example.cadastro',
  );
}
